server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d70gc1v5gffc73ds87f0-a:5432/esports_platform
spring.datasource.username=esports_platform_user
spring.datasource.password=wWULqcthgAB5ig3cKjBsnVzOyFEoHi5T
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
logging.level.com.esports=DEBUG
